apiVersion: v1
kind: Endpoints
metadata:
 name: glusterfs-cluster
subsets:
 - addresses:
   - ip: 10.0.2.30
   ports:
   - port: 1
     protocol: TCP
 - addresses:
   - ip: 10.0.2.31
   ports:
   - port: 1
     protocol: TCP
