kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gluster-dyn
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.110.214.165:8080"
  restauthenabled: "false"
  volumetype: "replicate:2"
